server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mail:
    host: localhost
    port: 1025  # MailHog порт для тестов
    username: test@test.com
    password: testpassword
    properties:
      mail:
        smtp:
          auth: false        # Для тестов false
          starttls:
            enable: false    # Для тестов false

kafka:
  topic:
    user-events: user-events

mail:
  from: no-reply@example.com

logging:
  level:
    com.example.notificationservice: DEBUG